### ISSUE TITLE
Problems with deeply nested async routes

### ISSUE THREAD

**Issue by Ortimis** [prescottprue/generator-react-firebase#107]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Integrating async routes with the getChildRoute method works like a charm. However integrating more deeply nested routes like `/projects/:id/settings` reveals some problems: The route is properly loaded as the `nextState` in `getComponent(nextState, cb)` shows `0
:
{path: "/", component: ƒ, indexRoute: {…}, childRoutes: Array(6)}
1
:
{path: "/projects", getComponent: ƒ, getChildRoutes: ƒ}
2
:
{path: ":projectname", getComponent: ƒ, getChildRoutes: ƒ}
3
:
{path: "settings", getComponent: ƒ}`

But it only renders the Component of the parent route (in this case `/src/routes/projects/routes/project/components/ProjectPage`)

**What is the expected behavior?**
It should render `/src/routes/projects/routes/project/routes/settings/components/SettingsPage`

Have you experienced similar issues? Ideas on solving it?

**Comment by prescottprue** [comment]
@Ortimis Did you make sure to include a `props.children` within your parent's render? If not, your child routes will not render. [That is currently happening for you in the projects page](https://github.com/prescottprue/generator-react-firebase/blob/master/examples/react-firebase-redux/src/routes/Projects/components/ProjectsPage/ProjectsPage.js#L21) when using the generator.

React's `cloneElement` is used so that props can be passed to each child.

Open to adding something in the docs to more clearly outline adding a route.

**Comment by Ortimis** [comment]
Oh right, that's it! Thank you so much
