### ISSUE TITLE
Feature Request - Add localized MUI theming

### ISSUE THREAD

**Issue by dustingraves** [prescottprue/generator-react-firebase#110]
With support added for the main theme customization of material ui, it would be nice to add an option for a localized theme configuration.

Currently I skip creating scss and add a `__name__.style.js` in the enhancer I use withStyles from material ui and apply the style from the `__name__.style.js file`.

```javascript
// __name__.style.js
export default theme => ({
  root: {
      // example style
  },
})
```
```javascript
// __name__.enhancer.js
import { compose } from 'redux'
import { withHandlers } from 'recompose'
import { withStyles } from '@material-ui/core/styles'
import style from './__name__.style'

export default compose(
  withHandlers({
    // someHandler: props => value => {}
  }),
  withStyles(style)
)
```

**Comment by prescottprue** [comment]
@dustingraves After looking at the material-ui docs a bunch, it seems like it might make more sense to call it `__name__.styles.js` since there can be multiple styles in there, so I went with that. Open to changing it though.

[`v2.0.5`](https://github.com/prescottprue/generator-react-firebase/releases/tag/v2.0.5) was published with a new question that now asks if you want localized MUI theming. Let me know if it doesn't work as expected.

**Comment by dustingraves** [comment]
That works great. Just nice to have the option in there.
