### ISSUE TITLE
New ProjectPage.enhancer is broken

### ISSUE THREAD

**Issue by dustingraves** [prescottprue/generator-react-firebase#120]
**Describe the bug**
Commit states `getVal` was changed to lodash `get` but `get` is not imported. `getVal` is still being imported and lint validation fails.

**To Reproduce**
Generate a new project and run `npm run lint` or just go look at `src/routes/Projects/routes/Project/components/ProjectPage/ProjectPage.enhancer`

**Expected behavior/code**
`get` should be imported from lodash and `getVal` removed.

```js
import { get } from 'lodash'
```

**Environment**
- Babel version(s): core 6.24.1 / loader 7.0.0
- Node/npm version: Node 10/npm 6.4.1
- OS: OS X 10.13.5
- Monorepo no
- How you are using Babel: loader (default)

**Possible Solution**
Add the import statement to the generated code.

**Additional context/Screenshots**

**Comment by prescottprue** [comment]
Thanks for reporting

**Comment by prescottprue** [comment]
The [v2.1.1 release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v2.1.1) has this fix and a few others. Make sure to run `npm i -g generator-react-firebase` to get then update. From there you should be able to run the generator again and only accept changes on the files you wish up update (if you have been making changes since then).

Thanks again for reaching out with the report!
