### ISSUE TITLE
broken tests, chai-enzyme: "Can't find variable: Map"

### ISSUE THREAD

**Issue by rm-rf-etc** [prescottprue/generator-react-firebase#126]
Seems that the tests don't work. No time available to investigate at the moment.

```
START:
11 10 2018 19:54:07.539:WARN [watcher]: Pattern "/Users/rob/clients/sunil_paul/dumo/node_modules/babel-polyfill/dist/polyfill.js" does not match any file.
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: Map
  at webpack:///node_modules/chai-enzyme/build/index.js:93:0 <- tests/test-bundler.js:82716
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: Map
  at webpack:///node_modules/chai-enzyme/build/index.js:93:0 <- tests/test-bundler.js:82716

Finished in 0.971 secs / 0 secs @ 19:54:30 GMT-0700 (Pacific Daylight Time)

SUMMARY:
✔ 0 tests completed

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
npm ERR! Test failed.  See above for more details.
```

**Comment by prescottprue** [comment]
Which version of `generator-react-firebase` did you use and what node version?

Currently working adding an option to use jest for tests instead of mocha/chai/karma. The tooling is much more simple and therefore easy to upkeep, but still interested to try to replicate this.

What are you hoping to get out of the tests? We have our E2E tests written in Cypress covering main application usage (going to make an option for this soon), so for us, the unit tests will mostly be useful for "Did thing change? If so what looks different?". Jest's snapshots are perfect for this, but the existing mocha/chai setup has only really been good for checking state/prop changes (which can also easily be done with Jest).

Either way, thanks for reaching out!

**Comment by rm-rf-etc** [comment]
Sorry for the slow response.

generator: 2.3.1
node: v10.11.0
OS: macOS Sierra 10.12.6
npm: 6.4.1
yarn: 1.10.0

Project dependancies were installed with yarn.

Initial focus with tests was utility/helper and selector functions. Rendering of components hasn't been a critical requirement for me yet, but I would definitely like to get that working to increase my code test coverage.

Thanks so much for this great tool! It's been very helpful.

**Comment by prescottprue** [comment]
@rm-rf-etc When installing from the `next` tag/branch there is now option for Jest tests for components as well as separate options for Cloud Functions tests (mocha) and UI Tests (Cypress).

The plan is to release it to `latest` soon, so I'm going to close. Let me know if it doesn't function as you would expect, thanks for reporting!
