### ISSUE TITLE
Inconsistent projects order

### ISSUE THREAD

**Issue by pshevtsov** [prescottprue/generator-react-firebase#194]
**Describe the bug**
Fatal error when generating a project

**To Reproduce**
When projects are created they are listed in inconsistent order

1. Generate app
1. Sign up and Login
1. Go to /projects
1. Create several projects

**Expected behavior/code**
Projects list has consistent order (by name or by creation timestamp)

**Additional Context/Screenshots**
![image](https://user-images.githubusercontent.com/290451/77283394-4a661e00-6cdd-11ea-8e05-1674c55099a4.png)

**Comment by prescottprue** [comment]
Nice idea here - that should be easy to add. Just out of curiosity, are you opting into Firestore? How about redux? Could you provide your list of answers to the generator?

**Comment by prescottprue** [comment]
If you are using Firestore, something to note is that running a query that looks for projects created by the current user and sorts by created time it will throw the following error (since indexes aren't setup):

![image](https://user-images.githubusercontent.com/2992224/77383737-f2f99980-6d40-11ea-9f8b-65096d036735.png)

Since the goal is to have things work out of the box, I am thinking this extra level of sorting may be good to leave out. What I could do though is place it on the query and comment that section out with a note about needing to enable the index - how does that sound?

**Comment by prescottprue** [comment]
In [v5.3.1](https://github.com/prescottprue/generator-react-firebase/releases/tag/v5.3.1) they are ordered by documentId, as mentioned ordering by createdAt was left out since it requires adding an index
