### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by michalens** [prescottprue/generator-react-firebase#303]
1. `npm install` fails, because it has react version 17, and many dependencies link to 16
2. If I manually change react and react-dom to 16.14.0, then I get this along with menu security vulnerabilities
![Screen Shot 2020-11-20 at 15 25 39](https://user-images.githubusercontent.com/42828375/99805141-baff5c00-2b44-11eb-9756-5dd94e5c9902.png)

**Comment by prescottprue** [comment]
Just to clarify - was this opting into redux?

Was it clear what dependencies were linked to 16 still?

**Comment by prescottprue** [comment]
It appears that react-redux-firebase is at least one of the dependencies that needs updating to support the new version. I would suggest trying to generate without redux for now while I look into it further

**Comment by michalens** [comment]
I installed without redux, still getting errors
![Screen Shot 2020-11-21 at 12 30 37](https://user-images.githubusercontent.com/42828375/99875080-80a1c780-2bf5-11eb-8c5f-d4c5451d194a.png)

**Comment by prescottprue** [comment]
@michalens That error appears to be due to an incompatible node version with what is set in `functions/package.json` - this defines the [cloud function runtime](https://cloud.google.com/functions/docs/writing/#the_cloud_functions_runtime) as described [in the firebase docs](https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version). This can only accept 10 or 12 (no ^ or anything)

You can do a few things to address the issue
* run`yarn install --ignore-engines` - this will ignore yarn's verification of node version while installing
* remove the `engines` section from `functions/package.json` (this may or may not cause a warning from the firebase cli when trying to deploy functions)
* switch to a compatible node version - If you have nvm installed you can install and switch to the newest 12 with `nvm install 12`. Then re-run install

All of the above said, it would be nice to have the project handle this by default. In the meantime I think it would be good to add a note in the README about this incase others bump into it

**Comment by prescottprue** [comment]
v7.5.0 was released for fixes to app when opting into redux (it was needing to cleanup some lint and update react-redux-firebase).

You will still need to handle the node 12 version as mentioned in the previous message - I found that this was already noted [in the FAQ section](https://github.com/prescottprue/generator-react-firebase#faq), but I added another note to the Getting Started section.

Please reach out if anything else isn't working as expected
