### ISSUE TITLE
Log-in not recognised when no display name

### ISSUE THREAD

**Issue by davej** [prescottprue/generator-react-firebase#51]
When adding a user through the Firebase admin it does not populate fields such as username or display name (just email). This generator will log in correctly but the main nav is not updated. See screenshot attached:

![logged-in](https://user-images.githubusercontent.com/26971/27860537-f8fd6670-6174-11e7-8523-0e19f1fb1e75.png)

**Comment by prescottprue** [comment]
@davej This is because the Navbar points to data which is within the `users` collection due to config telling `react-redux-firebase` to do that.

It is possible to show Account dropdown in the Navbar even if no profile is available, is that what you are suggesting the behavior should be?

Thanks for the input, if I am understanding correctly, this shouldn't be too difficult to implement.

**Comment by davej** [comment]
Yes, even if there is no profile data then I think the main nav should still be in the 'logged-in' state. Is it possible to also fallback to display the email address when the display name isn't available?

**Comment by prescottprue** [comment]
[`v1.3.0`](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.3.0) was released with this and a ton of other improvements.

Now no account is supported, as well as one without a display name. Also, the avatar/buttons do not appear until data is loaded now, so there is no flicker.

**Comment by prescottprue** [comment]
[`v1.3.1`] also includes the change. It also uses prop-types instead of getting it from react, which makes the warnings disappear.
